export interface LocationNode {
  id: string;
  name: string;
  state: string;
  country: string;
  continent: string;
  lat: number;
  lng: number;
  status: "Healthy" | "Watch" | "Critical";
  revenue: number;
  target: number;
  manager: string;
  storesCount: number;
  nps: number;
}

export function haversineDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c);
}

export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "Delhi NCR"
];

export const INTERNATIONAL_COUNTRIES = [
  "United States", "United Kingdom", "United Arab Emirates", "Japan",
  "Australia", "Canada", "Germany", "France", "Singapore", "Brazil",
  "South Africa", "Saudi Arabia", "South Korea", "Switzerland"
];

export const GLOBAL_LOCATIONS: LocationNode[] = [
  // ── INDIA (28 STATES & UTS) ──────────────────────────────────────────
  {
    id: "in-mh-pune",
    name: "Pune HQ Central",
    state: "Maharashtra",
    country: "India",
    continent: "Asia",
    lat: 18.5204,
    lng: 73.8567,
    status: "Healthy",
    revenue: 154000,
    target: 150000,
    manager: "Rahul Sharma",
    storesCount: 12,
    nps: 94,
  },
  {
    id: "in-mh-mumbai",
    name: "Mumbai Central",
    state: "Maharashtra",
    country: "India",
    continent: "Asia",
    lat: 19.0760,
    lng: 72.8777,
    status: "Healthy",
    revenue: 210000,
    target: 180000,
    manager: "Amit Patel",
    storesCount: 18,
    nps: 96,
  },
  {
    id: "in-mh-nashik",
    name: "Nashik City Center",
    state: "Maharashtra",
    country: "India",
    continent: "Asia",
    lat: 19.9975,
    lng: 73.7898,
    status: "Watch",
    revenue: 88000,
    target: 100000,
    manager: "Priya Verma",
    storesCount: 4,
    nps: 81,
  },
  {
    id: "in-dl-delhi",
    name: "Delhi Connaught Place",
    state: "Delhi NCR",
    country: "India",
    continent: "Asia",
    lat: 28.6139,
    lng: 77.2090,
    status: "Critical",
    revenue: 64000,
    target: 120000,
    manager: "Vikram Singh",
    storesCount: 15,
    nps: 68,
  },
  {
    id: "in-ka-bangalore",
    name: "Bangalore Indiranagar",
    state: "Karnataka",
    country: "India",
    continent: "Asia",
    lat: 12.9716,
    lng: 77.5946,
    status: "Healthy",
    revenue: 185000,
    target: 170000,
    manager: "Sneha Rao",
    storesCount: 14,
    nps: 92,
  },
  {
    id: "in-tn-chennai",
    name: "Chennai Anna Nagar",
    state: "Tamil Nadu",
    country: "India",
    continent: "Asia",
    lat: 13.0827,
    lng: 80.2707,
    status: "Healthy",
    revenue: 138000,
    target: 130000,
    manager: "Karthik Raja",
    storesCount: 8,
    nps: 90,
  },
  {
    id: "in-wb-kolkata",
    name: "Kolkata Park Street",
    state: "West Bengal",
    country: "India",
    continent: "Asia",
    lat: 22.5726,
    lng: 88.3639,
    status: "Watch",
    revenue: 95000,
    target: 110000,
    manager: "Sourav Banerjee",
    storesCount: 6,
    nps: 84,
  },
  {
    id: "in-tg-hyderabad",
    name: "Hyderabad Cyberabad",
    state: "Telangana",
    country: "India",
    continent: "Asia",
    lat: 17.3850,
    lng: 78.4867,
    status: "Healthy",
    revenue: 142000,
    target: 140000,
    manager: "Ananya Reddy",
    storesCount: 9,
    nps: 89,
  },
  {
    id: "in-gj-ahmedabad",
    name: "Ahmedabad SG Highway",
    state: "Gujarat",
    country: "India",
    continent: "Asia",
    lat: 23.0225,
    lng: 72.5714,
    status: "Healthy",
    revenue: 125000,
    target: 120000,
    manager: "Jignesh Shah",
    storesCount: 7,
    nps: 91,
  },
  {
    id: "in-rj-jaipur",
    name: "Jaipur Malviya Nagar",
    state: "Rajasthan",
    country: "India",
    continent: "Asia",
    lat: 26.9124,
    lng: 75.7873,
    status: "Watch",
    revenue: 82000,
    target: 95000,
    manager: "Rathore Singh",
    storesCount: 5,
    nps: 82,
  },
  {
    id: "in-up-lucknow",
    name: "Lucknow Hazratganj",
    state: "Uttar Pradesh",
    country: "India",
    continent: "Asia",
    lat: 26.8467,
    lng: 80.9462,
    status: "Healthy",
    revenue: 110000,
    target: 105000,
    manager: "Alok Mishra",
    storesCount: 6,
    nps: 88,
  },
  {
    id: "in-kl-kochi",
    name: "Kochi Marine Drive",
    state: "Kerala",
    country: "India",
    continent: "Asia",
    lat: 9.9312,
    lng: 76.2673,
    status: "Healthy",
    revenue: 118000,
    target: 110000,
    manager: "Nair Kurup",
    storesCount: 5,
    nps: 93,
  },
  {
    id: "in-pb-chandigarh",
    name: "Chandigarh Sector 17",
    state: "Punjab",
    country: "India",
    continent: "Asia",
    lat: 30.7333,
    lng: 76.7794,
    status: "Healthy",
    revenue: 104000,
    target: 100000,
    manager: "Gurpreet Singh",
    storesCount: 4,
    nps: 89,
  },
  {
    id: "in-ga-panaji",
    name: "Goa Panaji Beach Promenade",
    state: "Goa",
    country: "India",
    continent: "Asia",
    lat: 15.4989,
    lng: 73.8278,
    status: "Healthy",
    revenue: 135000,
    target: 120000,
    manager: "Mario D'Souza",
    storesCount: 3,
    nps: 95,
  },
  {
    id: "in-as-guwahati",
    name: "Guwahati GS Road",
    state: "Assam",
    country: "India",
    continent: "Asia",
    lat: 26.1445,
    lng: 91.7362,
    status: "Watch",
    revenue: 76000,
    target: 85000,
    manager: "Biren Sarma",
    storesCount: 3,
    nps: 80,
  },
  {
    id: "in-or-bhubaneswar",
    name: "Bhubaneswar Saheed Nagar",
    state: "Odisha",
    country: "India",
    continent: "Asia",
    lat: 20.2961,
    lng: 85.8245,
    status: "Healthy",
    revenue: 92000,
    target: 90000,
    manager: "Pradeep Mohanty",
    storesCount: 4,
    nps: 87,
  },
  {
    id: "in-jk-srinagar",
    name: "Srinagar Lal Chowk",
    state: "Jammu & Kashmir",
    country: "India",
    continent: "Asia",
    lat: 34.0837,
    lng: 74.7973,
    status: "Watch",
    revenue: 68000,
    target: 80000,
    manager: "Tariq Bhat",
    storesCount: 2,
    nps: 83,
  },
  {
    id: "in-br-patna",
    name: "Patna Boring Road",
    state: "Bihar",
    country: "India",
    continent: "Asia",
    lat: 25.5941,
    lng: 85.1376,
    status: "Watch",
    revenue: 72000,
    target: 85000,
    manager: "Rajesh Kumar",
    storesCount: 3,
    nps: 79,
  },
  {
    id: "in-mp-bhopal",
    name: "Bhopal MP Nagar",
    state: "Madhya Pradesh",
    country: "India",
    continent: "Asia",
    lat: 23.2599,
    lng: 77.4126,
    status: "Healthy",
    revenue: 89000,
    target: 85000,
    manager: "Sanjay Chouhan",
    storesCount: 4,
    nps: 86,
  },

  // ── INTERNATIONAL HUBS (USA, UK, UAE, JAPAN, GERMANY, ETC.) ─────────
  {
    id: "us-ny-manhattan",
    name: "New York Times Square",
    state: "New York",
    country: "United States",
    continent: "North America",
    lat: 40.7128,
    lng: -74.0060,
    status: "Healthy",
    revenue: 340000,
    target: 300000,
    manager: "John Miller",
    storesCount: 10,
    nps: 96,
  },
  {
    id: "us-ca-sanfrancisco",
    name: "San Francisco Market St",
    state: "California",
    country: "United States",
    continent: "North America",
    lat: 37.7749,
    lng: -122.4194,
    status: "Healthy",
    revenue: 310000,
    target: 280000,
    manager: "Sarah Jenkins",
    storesCount: 8,
    nps: 94,
  },
  {
    id: "us-tx-austin",
    name: "Austin Downtown",
    state: "Texas",
    country: "United States",
    continent: "North America",
    lat: 30.2672,
    lng: -97.7431,
    status: "Healthy",
    revenue: 260000,
    target: 240000,
    manager: "David Ross",
    storesCount: 6,
    nps: 92,
  },
  {
    id: "uk-ld-london",
    name: "London Oxford Street",
    state: "Greater London",
    country: "United Kingdom",
    continent: "Europe",
    lat: 51.5074,
    lng: -0.1278,
    status: "Healthy",
    revenue: 290000,
    target: 270000,
    manager: "Oliver Wright",
    storesCount: 9,
    nps: 93,
  },
  {
    id: "uae-db-dubai",
    name: "Dubai Downtown Mall",
    state: "Dubai",
    country: "United Arab Emirates",
    continent: "Asia",
    lat: 25.2048,
    lng: 55.2708,
    status: "Healthy",
    revenue: 380000,
    target: 320000,
    manager: "Tariq Al-Mansoor",
    storesCount: 12,
    nps: 98,
  },
  {
    id: "jp-tk-tokyo",
    name: "Tokyo Shibuya Crossing",
    state: "Tokyo Prefecture",
    country: "Japan",
    continent: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    status: "Healthy",
    revenue: 360000,
    target: 310000,
    manager: "Kenji Sato",
    storesCount: 11,
    nps: 97,
  },
  {
    id: "au-nsw-sydney",
    name: "Sydney Circular Quay",
    state: "New South Wales",
    country: "Australia",
    continent: "Oceania",
    lat: -33.8688,
    lng: 151.2093,
    status: "Healthy",
    revenue: 270000,
    target: 250000,
    manager: "Liam O'Connor",
    storesCount: 7,
    nps: 91,
  },
  {
    id: "de-be-berlin",
    name: "Berlin Alexanderplatz",
    state: "Berlin",
    country: "Germany",
    continent: "Europe",
    lat: 52.5200,
    lng: 13.4050,
    status: "Healthy",
    revenue: 240000,
    target: 230000,
    manager: "Lukas Weber",
    storesCount: 5,
    nps: 90,
  },
  {
    id: "sg-sg-marina",
    name: "Singapore Marina Bay",
    state: "Central Region",
    country: "Singapore",
    continent: "Asia",
    lat: 1.3521,
    lng: 103.8198,
    status: "Healthy",
    revenue: 330000,
    target: 290000,
    manager: "Wei Chen",
    storesCount: 8,
    nps: 96,
  },
];
